import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData } from "react-router";
import db from "../db.server";
import { authenticate } from "../shopify.server";
import { AdminStyles, StatusBadge } from "../components/admin-ui";
import { getAdminConfiguration, issueMerchantCredential, updateSettingsModule } from "../subscriptions/admin-config";

const SECTIONS = [["general","General"],["widget","Widget"],["notifications","Notifications"],["installation","Installation"],["integrations","Integrations"],["api","API & webhooks"],["advanced","Advanced"]] as const;

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request); const url = new URL(request.url); const section = url.searchParams.get("section") || "general";
  const [configuration, credential, webhooks] = await Promise.all([
    getAdminConfiguration(db, session.shop), db.merchantApiCredential.findUnique({ where: { shopDomain: session.shop } }), db.merchantWebhook.findMany({ where: { shopDomain: session.shop }, orderBy: { createdAt: "desc" } }),
  ]);
  return { ...configuration, credential, webhooks, section, shop: session.shop };
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const { session } = await authenticate.admin(request); const form = await request.formData(); const intent = String(form.get("intent"));
  try {
    if (intent === "general") {
      await db.subscriptionSettings.update({ where: { shopDomain: session.shop }, data: {
        defaultDurationMonths: bounded(form, "defaultDurationMonths", 1, 120), activationTtlHours: bounded(form, "activationTtlHours", 1, 168),
        retryDay3: bounded(form, "retryDay3", 1, 30), retryDay7: bounded(form, "retryDay7", 1, 30), autoCancelDays: bounded(form, "autoCancelDays", 1, 90), expiryReminderDays: bounded(form, "expiryReminderDays", 1, 365),
        schedulerEnabled: form.has("schedulerEnabled"), whatsappEnabled: form.has("whatsappEnabled"), emailEnabled: form.has("emailEnabled"), successfulRenewalWhatsapp: form.has("successfulRenewalWhatsapp"),
      } });
    } else if (intent === "widget") {
      const current = (await getAdminConfiguration(db, session.shop)).modules.widget;
      await updateSettingsModule(db, session.shop, "widget", { ...current, heading: String(form.get("heading")), description: String(form.get("description")), buttonLabel: String(form.get("buttonLabel")), design: String(form.get("design")), accentColor: String(form.get("accentColor")), borderColor: String(form.get("borderColor")), backgroundColor: String(form.get("backgroundColor")), textColor: String(form.get("textColor")), showSavingsBadge: form.has("showSavingsBadge"), showOneTimeFirst: form.has("showOneTimeFirst"), hideSingleIntervalSelector: form.has("hideSingleIntervalSelector"), updateDisplayedProductPrice: form.has("updateDisplayedProductPrice"), customCss: String(form.get("customCss") || ""), disabledPathFragments: lines(form.get("disabledPathFragments")) });
    } else if (intent === "notifications") {
      const current = (await getAdminConfiguration(db, session.shop)).modules.notifications;
      await updateSettingsModule(db, session.shop, "notifications", { ...current, customerEmailEnabled: form.has("customerEmailEnabled"), customerWhatsappEnabled: form.has("customerWhatsappEnabled"), adminEmail: String(form.get("adminEmail") || ""), preDebitDays: numbers(form.get("preDebitDays"), 1, 34), preDebitHours: numbers(form.get("preDebitHours"), 1, 23), notifyBillingSuccess: form.has("notifyBillingSuccess"), notifyBillingFailure: form.has("notifyBillingFailure"), notifyStockout: form.has("notifyStockout"), notifyPauseResume: form.has("notifyPauseResume"), notifyCancellation: form.has("notifyCancellation"), notifyExpiry: form.has("notifyExpiry"), adminNewSubscription: form.has("adminNewSubscription"), adminPaymentFailure: form.has("adminPaymentFailure"), adminCustomerChange: form.has("adminCustomerChange"), adminStockout: form.has("adminStockout"), adminJobFailure: form.has("adminJobFailure") });
    } else if (intent === "installation") {
      const current = (await getAdminConfiguration(db, session.shop)).modules.installation;
      await updateSettingsModule(db, session.shop, "installation", { ...current, themeBlockInstalled: form.has("themeBlockInstalled"), thankYouBlockInstalled: form.has("thankYouBlockInstalled"), orderStatusBlockInstalled: form.has("orderStatusBlockInstalled"), accountPageInstalled: form.has("accountPageInstalled"), accountMenuInstalled: form.has("accountMenuInstalled"), lastVerifiedAt: new Date().toISOString() });
    } else if (intent === "integrations") {
      const current = (await getAdminConfiguration(db, session.shop)).modules.integrations;
      await updateSettingsModule(db, session.shop, "integrations", { ...current, googleAnalyticsId: String(form.get("googleAnalyticsId") || ""), klaviyoEnabled: form.has("klaviyoEnabled"), klaviyoPublicKey: String(form.get("klaviyoPublicKey") || ""), includeMagicLinkInEvents: form.has("includeMagicLinkInEvents"), gorgiasEnabled: form.has("gorgiasEnabled"), attentiveEnabled: form.has("attentiveEnabled"), orderTags: lines(form.get("orderTags")), customerActiveTag: String(form.get("customerActiveTag")), customerPausedTag: String(form.get("customerPausedTag")), customerInactiveTag: String(form.get("customerInactiveTag")) });
    } else if (intent === "advanced") {
      const current = (await getAdminConfiguration(db, session.shop)).modules.advanced;
      await updateSettingsModule(db, session.shop, "advanced", { ...current, automaticallyDeleteCancelledAfterDays: bounded(form, "automaticallyDeleteCancelledAfterDays", 0, 3650), propagateProductTitlesAndSkus: form.has("propagateProductTitlesAndSkus"), propagateCurrentPrices: form.has("propagateCurrentPrices"), recalculateShippingAfterAddressChange: form.has("recalculateShippingAfterAddressChange"), recalculateShippingAfterLineRemoval: form.has("recalculateShippingAfterLineRemoval"), recalculateShippingAfterProfileChange: form.has("recalculateShippingAfterProfileChange"), shippingMethodName: String(form.get("shippingMethodName")), dateFormat: String(form.get("dateFormat")) });
    } else if (intent === "rotate_api") {
      const issued = issueMerchantCredential(); await db.merchantApiCredential.upsert({ where: { shopDomain: session.shop }, create: { shopDomain: session.shop, enabled: true, tokenHash: issued.tokenHash, secretHash: issued.secretHash, tokenLast4: issued.tokenLast4, rotatedAt: new Date() }, update: { enabled: true, tokenHash: issued.tokenHash, secretHash: issued.secretHash, tokenLast4: issued.tokenLast4, rotatedAt: new Date() } });
      return { ok: true, message: "New API credential issued. Copy it now; it will not be shown again.", credential: { token: issued.token, secret: issued.secret } };
    } else if (intent === "disable_api") await db.merchantApiCredential.updateMany({ where: { shopDomain: session.shop }, data: { enabled: false } });
    else if (intent === "add_webhook") await db.merchantWebhook.create({ data: { shopDomain: session.shop, name: String(form.get("name")), url: new URL(String(form.get("url"))).toString(), topics: form.getAll("topics").map(String) } });
    else if (intent === "delete_webhook") await db.merchantWebhook.deleteMany({ where: { id: String(form.get("id")), shopDomain: session.shop } });
    else throw new Error("Unknown settings action.");
    return { ok: true, message: "Settings saved." };
  } catch (error) { return { ok: false, message: error instanceof Error ? error.message : "Could not save settings." }; }
};

export default function SettingsPage() { const data = useLoaderData<typeof loader>(); const result = useActionData<typeof action>(); const widget = data.modules.widget, notifications = data.modules.notifications, installation = data.modules.installation, integrations = data.modules.integrations, advanced = data.modules.advanced; return <s-page heading="Settings"><AdminStyles/><s-stack direction="block" gap="base">
  {result ? <s-banner tone={result.ok ? "success" : "critical"}>{result.message}</s-banner> : null}
  {result && "credential" in result && result.credential ? <s-banner tone="warning"><p>API token: <code>{result.credential.token}</code></p><p>API secret: <code>{result.credential.secret}</code></p></s-banner> : null}
  <div className="es-tabs">{SECTIONS.map(([value,label]) => <a key={value} href={`/app/settings?section=${value}`} aria-current={data.section === value ? "page" : undefined}>{label}</a>)}</div>
  {data.section === "general" ? <s-section heading="Subscription engine"><Form method="post"><input type="hidden" name="intent" value="general"/><div className="es-form-grid"><label>Default duration (months)<br/><input type="number" name="defaultDurationMonths" min="1" max="120" defaultValue={data.settings.defaultDurationMonths}/></label><label>Activation link expiry (hours)<br/><input type="number" name="activationTtlHours" min="1" max="168" defaultValue={data.settings.activationTtlHours}/></label><label>First retry day<br/><input type="number" name="retryDay3" defaultValue={data.settings.retryDay3}/></label><label>Second retry day<br/><input type="number" name="retryDay7" defaultValue={data.settings.retryDay7}/></label><label>Auto-cancel after failure (days)<br/><input type="number" name="autoCancelDays" defaultValue={data.settings.autoCancelDays}/></label><label>Expiry reminder (days)<br/><input type="number" name="expiryReminderDays" defaultValue={data.settings.expiryReminderDays}/></label></div><p><label><input type="checkbox" name="schedulerEnabled" defaultChecked={data.settings.schedulerEnabled}/> Renewal scheduler is configured and enabled</label></p><p><label><input type="checkbox" name="whatsappEnabled" defaultChecked={data.settings.whatsappEnabled}/> WhatsApp notifications</label> · <label><input type="checkbox" name="successfulRenewalWhatsapp" defaultChecked={data.settings.successfulRenewalWhatsapp}/> Successful-renewal WhatsApp</label> · <label><input type="checkbox" name="emailEnabled" defaultChecked={data.settings.emailEnabled}/> Transactional email</label></p><s-button type="submit" variant="primary">Save general settings</s-button></Form></s-section> : null}
  {data.section === "widget" ? <s-section heading="Product-page subscription widget"><Form method="post"><input type="hidden" name="intent" value="widget"/><div className="es-form-grid"><label>Heading<br/><input name="heading" defaultValue={widget.heading}/></label><label>Button label<br/><input name="buttonLabel" defaultValue={widget.buttonLabel}/></label><label>Design<br/><select name="design" defaultValue={widget.design}><option value="default">Default</option><option value="compact">Compact</option><option value="card">Card</option></select></label><label>Accent<br/><input type="color" name="accentColor" defaultValue={widget.accentColor}/></label><label>Border<br/><input type="color" name="borderColor" defaultValue={widget.borderColor}/></label><label>Background<br/><input type="color" name="backgroundColor" defaultValue={widget.backgroundColor}/></label><label>Text<br/><input type="color" name="textColor" defaultValue={widget.textColor}/></label></div><p><label>Description<br/><textarea name="description" rows={3} defaultValue={widget.description}/></label></p><p><label><input type="checkbox" name="showSavingsBadge" defaultChecked={widget.showSavingsBadge}/> Show savings</label> · <label><input type="checkbox" name="showOneTimeFirst" defaultChecked={widget.showOneTimeFirst}/> Explain first order is full price</label> · <label><input type="checkbox" name="hideSingleIntervalSelector" defaultChecked={widget.hideSingleIntervalSelector}/> Hide selector for one interval</label> · <label><input type="checkbox" name="updateDisplayedProductPrice" defaultChecked={widget.updateDisplayedProductPrice}/> Update displayed price</label></p><p><label>Disabled URL fragments (one per line)<br/><textarea name="disabledPathFragments" rows={3} defaultValue={widget.disabledPathFragments.join("\n")}/></label></p><p><label>Custom CSS<br/><textarea name="customCss" rows={8} defaultValue={widget.customCss}/></label></p><s-button type="submit" variant="primary">Save widget</s-button></Form></s-section> : null}
  {data.section === "notifications" ? <s-section heading="Notification sequences"><Form method="post"><input type="hidden" name="intent" value="notifications"/><div className="es-form-grid"><label>Admin email<br/><input type="email" name="adminEmail" defaultValue={notifications.adminEmail}/></label><label>Pre-debit days (comma-separated)<br/><input name="preDebitDays" defaultValue={notifications.preDebitDays.join(",")}/></label><label>Pre-debit hours (comma-separated)<br/><input name="preDebitHours" defaultValue={notifications.preDebitHours.join(",")}/></label></div><p><label><input type="checkbox" name="customerEmailEnabled" defaultChecked={notifications.customerEmailEnabled}/> Customer email</label> · <label><input type="checkbox" name="customerWhatsappEnabled" defaultChecked={notifications.customerWhatsappEnabled}/> Customer WhatsApp</label></p><div className="es-form-grid">{[["notifyBillingSuccess","Renewal success"],["notifyBillingFailure","Renewal failure"],["notifyStockout","Stockout"],["notifyPauseResume","Pause/resume"],["notifyCancellation","Cancellation"],["notifyExpiry","Expiry"],["adminNewSubscription","Admin: new subscription"],["adminPaymentFailure","Admin: payment failure"],["adminCustomerChange","Admin: customer change"],["adminStockout","Admin: stockout"],["adminJobFailure","Admin: job failure"]].map(([key,label]) => <label key={key}><input type="checkbox" name={key} defaultChecked={notifications[key as keyof typeof notifications] as boolean}/>{" "}{label}</label>)}</div><p><s-button type="submit" variant="primary">Save notifications</s-button></p></Form></s-section> : null}
  {data.section === "installation" ? <s-section heading="Theme and checkout installation"><s-banner tone="warning">These checks document installation state. Use Shopify’s theme editor and checkout editor links to add/remove blocks; the master switch remains the final launch control.</s-banner><Form method="post"><input type="hidden" name="intent" value="installation"/><div className="es-form-grid">{[["themeBlockInstalled","Product widget / app embed"],["thankYouBlockInstalled","Thank-you activation block"],["orderStatusBlockInstalled","Order-status activation block"],["accountPageInstalled","Customer account page"],["accountMenuInstalled","Customer account menu"]].map(([key,label]) => <label key={key}><input type="checkbox" name={key} defaultChecked={installation[key as keyof typeof installation] as boolean}/>{" "}{label}</label>)}</div><p><div className="es-actions"><s-button href={`https://admin.shopify.com/store/${data.shop.replace(/\.myshopify\.com$/, "")}/themes/current/editor`} target="_blank">Open theme editor</s-button><s-button href={`https://admin.shopify.com/store/${data.shop.replace(/\.myshopify\.com$/, "")}/settings/checkout/editor`} target="_blank">Open checkout editor</s-button><s-button type="submit" variant="primary">Save verification</s-button></div></p></Form></s-section> : null}
  {data.section === "integrations" ? <s-section heading="Integrations and tags"><Form method="post"><input type="hidden" name="intent" value="integrations"/><div className="es-form-grid"><label>Google Analytics measurement ID<br/><input name="googleAnalyticsId" defaultValue={integrations.googleAnalyticsId}/></label><label>Klaviyo public key<br/><input name="klaviyoPublicKey" defaultValue={integrations.klaviyoPublicKey}/></label><label>Active customer tag<br/><input name="customerActiveTag" defaultValue={integrations.customerActiveTag}/></label><label>Paused customer tag<br/><input name="customerPausedTag" defaultValue={integrations.customerPausedTag}/></label><label>Inactive customer tag<br/><input name="customerInactiveTag" defaultValue={integrations.customerInactiveTag}/></label></div><p><label><input type="checkbox" name="klaviyoEnabled" defaultChecked={integrations.klaviyoEnabled}/> Klaviyo events</label> · <label><input type="checkbox" name="includeMagicLinkInEvents" defaultChecked={integrations.includeMagicLinkInEvents}/> Include portal magic link</label> · <label><input type="checkbox" name="gorgiasEnabled" defaultChecked={integrations.gorgiasEnabled}/> Gorgias</label> · <label><input type="checkbox" name="attentiveEnabled" defaultChecked={integrations.attentiveEnabled}/> Attentive</label></p><p><label>Shopify order tags (one per line)<br/><textarea name="orderTags" rows={4} defaultValue={integrations.orderTags.join("\n")}/></label></p><s-button type="submit" variant="primary">Save integrations</s-button></Form></s-section> : null}
  {data.section === "api" ? <><s-section heading="Merchant API"><s-paragraph>Status: <StatusBadge status={data.credential?.enabled ? "active" : "disabled"}/> {data.credential?.tokenLast4 ? `· token ending ${data.credential.tokenLast4}` : ""}</s-paragraph><div className="es-actions"><Form method="post"><button name="intent" value="rotate_api">Issue / rotate credential</button></Form>{data.credential?.enabled ? <Form method="post"><button name="intent" value="disable_api">Disable API</button></Form> : null}</div></s-section><s-section heading="Outgoing webhooks"><Form method="post"><input type="hidden" name="intent" value="add_webhook"/><div className="es-form-grid"><label>Name<br/><input name="name" required/></label><label>HTTPS URL<br/><input type="url" name="url" required/></label></div><p>{["subscription.created","subscription.updated","subscription.cancelled","renewal.succeeded","renewal.failed"].map((topic) => <label key={topic}><input type="checkbox" name="topics" value={topic}/>{" "}{topic} · </label>)}</p><s-button type="submit" variant="primary">Add webhook</s-button></Form><div className="es-table-wrap"><table className="es-table"><thead><tr><th>Name</th><th>URL</th><th>Topics</th><th>Status</th><th>Failures</th><th></th></tr></thead><tbody>{data.webhooks.length ? data.webhooks.map((hook) => <tr key={hook.id}><td>{hook.name}</td><td>{hook.url}</td><td>{Array.isArray(hook.topics) ? hook.topics.join(", ") : ""}</td><td><StatusBadge status={hook.status}/></td><td>{hook.failureCount}</td><td><Form method="post"><input type="hidden" name="id" value={hook.id}/><button name="intent" value="delete_webhook">Delete</button></Form></td></tr>) : <tr><td colSpan={6}>No outgoing webhooks.</td></tr>}</tbody></table></div></s-section></> : null}
  {data.section === "advanced" ? <s-section heading="Advanced behavior"><Form method="post"><input type="hidden" name="intent" value="advanced"/><div className="es-form-grid"><label>Delete cancelled records after days (0 = retain)<br/><input type="number" name="automaticallyDeleteCancelledAfterDays" min="0" defaultValue={advanced.automaticallyDeleteCancelledAfterDays}/></label><label>Shipping method name<br/><input name="shippingMethodName" defaultValue={advanced.shippingMethodName}/></label><label>Date format<br/><select name="dateFormat" defaultValue={advanced.dateFormat}><option value="automatic">Automatic</option><option value="dd/mm/yyyy">DD/MM/YYYY</option><option value="yyyy-mm-dd">YYYY-MM-DD</option><option value="mm/dd/yyyy">MM/DD/YYYY</option></select></label></div><div className="es-form-grid">{[["propagateProductTitlesAndSkus","Sync latest titles and SKUs"],["propagateCurrentPrices","Charge current Shopify prices"],["recalculateShippingAfterAddressChange","Recalculate shipping after address change"],["recalculateShippingAfterLineRemoval","Recalculate after SKU removal"],["recalculateShippingAfterProfileChange","Recalculate after delivery profile change"]].map(([key,label]) => <label key={key}><input type="checkbox" name={key} defaultChecked={advanced[key as keyof typeof advanced] as boolean}/>{" "}{label}</label>)}</div><p><s-button type="submit" variant="primary">Save advanced settings</s-button></p></Form></s-section> : null}
</s-stack></s-page>; }

function bounded(form: FormData, key: string, min: number, max: number) { const value = Number(form.get(key)); if (!Number.isInteger(value) || value < min || value > max) throw new Error(`${key} must be between ${min} and ${max}.`); return value; }
function lines(value: FormDataEntryValue | null) { return String(value || "").split(/\r?\n/).map((item) => item.trim()).filter(Boolean); }
function numbers(value: FormDataEntryValue | null, min: number, max: number) { const parsed = String(value || "").split(",").map((item) => Number(item.trim())).filter((item) => Number.isInteger(item) && item >= min && item <= max); return [...new Set(parsed)].slice(0,3); }
