# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "178d46f3de67e7e494a14134b15d5b7f"
name = "earthen-subscriptions"
application_url = "https://earthen-subscriptions-app-768696379805.asia-south1.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_draft_orders,write_orders"

[auth]
redirect_urls = [ "https://earthen-subscriptions-app-768696379805.asia-south1.run.app/auth/callback" ]

[app_proxy]
url = "https://earthen-subscriptions-app-768696379805.asia-south1.run.app/apps/subscriptions"
prefix = "apps"
subpath = "subscriptions"
