# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "021d4d26601c29f21ada97ca6c70aa08"
name = "earthen-loyalty-app"
application_url = "https://earthen-loyalty-app-x5vmupepiq-el.a.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/customers/update"

  [[webhooks.subscriptions]]
  topics = [ "customers/delete" ]
  uri = "/webhooks/customers/delete"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "fulfillment_events/create" ]
  uri = "/webhooks/fulfillment_events/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,read_fulfillments,read_discounts,write_discounts"

[auth]
redirect_urls = [ "https://earthen-loyalty-app-x5vmupepiq-el.a.run.app/auth/callback" ]

[app_proxy]
url = "https://earthen-loyalty-app-x5vmupepiq-el.a.run.app/apps/loyalty"
prefix = "apps"
subpath = "loyalty"
